application: falcr
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /dist
  static_dir: dist
- url: /login
  script: falcr.app.api
- url: /quote
  script: falcr.app.api
- url: /
  static_files: index.html
  upload: index\.html
